01-SourceCode/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

01-SourceCode/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
# from editer import views
from blog import views
from index import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

# 引用sitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('index.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                  path('account/', include('account.urls')),  # 导入account用户系统
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  # url(r'^blog/', views.blog),  # 测试获取后台编辑的内容用的
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 没有这一句无法显示上传的图片

01-SourceCode/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset() \
            .filter(status='published')


# 发帖、邮件传送等模型
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # body = models.TextField()
    body = RichTextUploadingField(default='', verbose_name='内容详情')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)  # 采用auto_now_add当创建某个对象时，日期自动保存
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()  # 引入tag标签

    # 模型的标准url
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


# 评论系统
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on{}'.format(self.name, self.post)

01-SourceCode/blog/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


# 创建前台评论表单
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


# 构建搜索视图
class SearchForm(forms.Form):
    query = forms.CharField()

01-SourceCode/blog/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger
# 使用基于类的视图，并使用Django提供的通用listview,这一基视图可显示任意类型的对象：
from django.views.generic import ListView
# 引入搜索表单
from django.contrib.postgres.search import SearchVector

# 邮件表单 评论表单
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


# Create your views here.

# 显示帖子列表
def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts': posts})


# 显示独立帖子
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # 当前帖子的评论列表以及发表等
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # 已表评论
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    # 相似性检索帖子
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]  # 检索前四个

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 三个一页
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果页面不是完整的，则生成第一页
        posts = paginator.page(1)
    except EmptyPage:
        # 如果页面超出范围，则传递结果的最后一页
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_share(request, post_id):
    # 检索帖子ID
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == "POST":
        # 表单发送
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # 表单字段通过验证
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@z01.com', [cd['to']])
            sent = True
            # 发送邮件
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


# 构建搜索视图
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(search=SearchVector('title', 'body'), ).filter(search=query)
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

01-SourceCode/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load sass_tags %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block banner %}
    <div class="blog_banner_div_con">
        <p>{{ post.title }}</p>
        <span><i class="zi zi_clock"></i> {{ post.publish|date:"Y-m-d"}}</span>
        <span><i class="zi zi_user"></i> {{ post.author }}</span>
        <span><i class="zi zi_comment"></i>{% with comments.count as total_comments %} {{ total_comments }}{% endwith %}</span>
        <span><a href="{% url "blog:post_share" post.id %}"><i class="zi zi_sharealt"></i></a></span>
    </div>{% endblock %}
{% block content %}
    <div class="detail">
    <div class="container-xl mt-4">
    <div class="row">
    <div class="col-md-9 col-12">
        <div class="detail_con">
            <ul class="breadcrumb">
                <li><a href="/">首页</a></li>
                <li><a href="/">Python</a></li>
                <li>正文</li>
            </ul>
            <hr>
{#            <h1>{{ post.title }}</h1>#}
{#            <p class="date">#}
{#                <i class="zi zi_clock"></i> {{ post.publish|date:"Y-m-d"}} 作者：{{ post.author }}#}
{#            </p>#}
         <small>Markdown解析：</small> {{ post.body|markdown }}
            <small>直接输出：</small> {{ post.body|linebreaks }}
            {{ post.body|safe }}
        </div>
        <div class="detail_comments">
            <div class="detail_comments_leave">
                {% for comment in comments %}
                    <div class="comment">
                    <p class="info">
                        {{ forloop.counter }} 楼{{ comment.name }}
                        {{ comment.created|date:"Y-m-d H:i:s"  }}
                    </p>
                    {{ comment.body|linebreaks }}
                    </div>
                    {% empty %}
                    <p>这里评论空空如也。 </p>
                {% endfor %}
            </div>
            <div class="detail_comments_liuyan">
                {% if new_comment %}
                <h3>你的评论成功发表</h3>
                {% else %}
                <span>发表评论:</span>
                <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input class="btn btn-outline-info" type="submit" value="发表评论" /> </p>
                </form>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-md-3 col-12">
        <div class="detail_user">
            <div class="detail_user_top">
                <div class="detail_user_top_img"><img src="{% sass_src 'images/user_img.jpg' %}" /></div>
            </div>
            <div class="detail_user_cen">yi夏</div>
            <div class="detail_user_bot">
                <div class="detail_user_bot1"><span>{% total_posts %}</span><p>文章</p></div>
                <div class="detail_user_bot1"><span>12</span><p>评论</p></div>
                <div class="detail_user_bot1"><span>40</span><p>标签</p></div>
            </div>
        </div>
        <div class="detail_huifu">
            <span class="detail_huifu_title">最新回复 <i class="zi zi_reply" zico="回复黑"></i></span>
            <ul>
                <li>
                    <a href="">
                    <img src="{% sass_src 'images/user_img.jpg' %}" />
                    <div class="detail_huifu_detail">
                        <div class="detail_huifu_detail_on"><div class="detail_huifu_detail_on1">李大侠</div><div class="detail_huifu_detail_on1">2021-01-01</div></div>
                        <div class="detail_huifu_detail_the">文章写的很棒，收藏了</div>
                    </div>
                    </a>
                </li>
                <li>
                    <a href="">
                    <img src="{% sass_src 'images/user_img.jpg' %}" />
                    <div class="detail_huifu_detail">
                        <div class="detail_huifu_detail_on"><div class="detail_huifu_detail_on1">王王王</div><div class="detail_huifu_detail_on1">2021-01-01</div></div>
                        <div class="detail_huifu_detail_the">简单明了,nice</div>
                    </div>
                    </a>
                </li>
                <li>
                    <a href="">
                    <img src="{% sass_src 'images/index_con02.jpg' %}" />
                    <div class="detail_huifu_detail">
                        <div class="detail_huifu_detail_on"><div class="detail_huifu_detail_on1">李大侠</div><div class="detail_huifu_detail_on1">2021-01-01</div></div>
                        <div class="detail_huifu_detail_the">文章写的很棒，收藏了</div>
                    </div>
                    </a>
                </li>
                <li>
                    <a href="">
                    <img src="{% sass_src 'images/user_img.jpg' %}" />
                    <div class="detail_huifu_detail">
                        <div class="detail_huifu_detail_on"><div class="detail_huifu_detail_on1">yixia</div><div class="detail_huifu_detail_on1">2021-01-01</div></div>
                        <div class="detail_huifu_detail_the">文章写的很棒，收藏了，收藏了，收藏了，收藏了，收藏了，收藏了</div>
                    </div>
                    </a>
                </li>
            </ul>
        </div>
        <div class="detail_random">
            <span class="detail_random_title">随便看看 <i class="zi zi_bookopen" zico="看书"></i></span>
            {% show_latest_random 3 %}
        </div>
    </div>
{#        <a href="{% url "blog:post_share" post.id %}">分享</a>#}
        {#    评论统计代码：#}

{#            相拟性帖子文章#}
{#            <hr>#}
{#            <h2>相关帖子</h2>#}
{#            {% for post in similar_posts %}#}
{#            <p>#}
{#                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>#}
{#            </p>#}
{#            {% empty %}#}
{#            无相似文章。#}
{#            {% endfor %}#}
    </div>
    </div>
    </div>
{% endblock %}

01-SourceCode/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

01-SourceCode/templates/blog/post/latest_random.html
{% load sass_tags %}
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}" target="_blank">
            <img src="{% sass_src 'images/index_con02.jpg' %}" />
        </a>
        <div class="detail_random_con">
            <span><i class="zi zi_clock"></i> {{ post.publish|date:"Y-m-d"}}</span>
            <p>{{ post.title }}</p>
        </div>
    </li>
    {% endfor %}
</ul>

01-SourceCode/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load sass_tags %}
{% block title %}我的博客_列表{% endblock %}
{% block banner %}<p>我的博客</p><span><a href="{% url "blog:post_feed" %}"><i class="zi zi_rss" zico="wifi黑"></i></a></span>{% endblock %}
{% block content %}

<div class="container-xl">
{% for post in posts %}
    <div class="blog_list">
        <a href="{{ post.get_absolute_url }}" target="_blank">
            <img src="{% sass_src 'images/index_con01.jpg' %}" alt="{{ post.title }}"/>
            <div class="blog_list_div">
                <div class="blog_list_div1">
                    <h1>{{ post.title }}</h1>
                    <span><i class="zi zi_clock"></i> {{ post.publish|date:"Y-m-d" }}</span>
                    <span> 作者：{{ post.author }}</span>
                    {% for tag in post.tags.all %}<a href="{% url "blog:post_list_by_tag" tag.slug %}" class="blog_list_div1_keyword"><i class="zi zi_tag" zico="标签黑"></i> {{ tag.name }}</a>{% endfor %}
                </div>
            </div>
        </a>
    </div>
{% endfor %}
{% include "pagination.html" with page=posts %}
</div>

<div class="banner_abvertising"><a href="/"></a></div>
{#广告banner end#}
<div class="container-xl">
    <div class="row">
        <div class="col-md-6 col-12">
            <div class="blog_list_con">
                <p>最近更新</p>
                {% show_latest_posts 4 %}
            </div>
        </div>
        <div class="col-md-6 col-12">
            <div class="blog_list_con">
                <p>最新热帖</p>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container-xl blog_img">
    <img src="{% sass_src 'images/index_con_list1.jpg' %}" />
</div>
{% endblock %}

{#{% block content1 %}#}
{#    {% if tag %}#}
{#    <h2>Posts tagged with:"{{ tag.name }}"</h2>#}
{#    {% endif %}#}
{##}
{#{% for post in posts %}#}
{#<h2>#}
{#<a href="{{ post.get_absolute_url }}">#}
{#    {{ post.title }}#}
{#</a>#}
{#</h2>#}
{#<p class="tages">关键字标签：#}
{#    {% for tag in post.tags.all %}#}
{#        <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>#}
{#    {% if not froloop.last %},{% endif %}#}
{#        {% endfor %}#}
{#    {{ post.tags.all|join:", " }}#}
{#</p>#}
{#    <p class="date">#}
{#    Published{{ post.publish }} by {{ post.author }}#}
{#    </p>#}
{#    <small>Markdown解析:</small>#}
{#    {{ post.body|markdown|truncatewords:30 }}#}
{#    <hr>#}
{#    <small>直接输出:</small>#}
{#    {{ post.body|truncatewords:30|linebreaks }}#}
{#{% endfor %}#}
{#    {% include "pagination.html" with page=posts %}#}
{#{% endblock %}#}

01-SourceCode/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}搜索{% endblock %}
{% block banner %}<p>从blog中检索...</p>{% endblock %}
{% block content %}
    <div class="container-xl search">
        <div class="search_results">
            {% if query %}
            <h1>关于“{{ query }}"的搜索结果如下：</h1>
            <h3>
                {% with results.count as total_results %}
                找到了 <span class="numcolor"> {{ total_results }}</span> 条结果 {# {{ total_results|pluralize }} #}
                {% endwith %}
            </h3>
                <ul>
                    {% for post in results %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">
                                <p class="search_list_title">{{ post.title }}<span class="search_list_deta"><i class="zi zi_clock" zico="时钟"></i> {{ post.publish|date:"Y-m-d" }}</span></p>
                                <p class="search_list_con">{{ post.body|truncatewords:7 }}</p>
                            </a>
                        </li>

{#                    <h4>#}
{#                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>#}
{#                    <span class="search_list_deta"></span>{{ post.publish|date:"Y-m-d" }}#}
{#                    </h4>#}
{#                        {{ post.body|truncatewords:10 }}#}
                    {% empty %}
                        <p>没有任何结果</p>
                        {% endfor %}
                </ul>
                <p class="zsearch">对结果不满意？<a href="{% url "blog:post_search" %}">再搜索</a></p>
                    {% else %}
        </div>
        <div class="search_input">
            <form action="." method="get">
                {{ form.as_p }}
    {#            <input type="submit"  value="搜索">#}
            <button class="search_button" type="submit"><i class="zi zi_search"></i></button>
            </form>
        </div>
        {%  endif %}
    </div>
{% endblock %}

01-SourceCode/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}分享一个好文章{% endblock %}
{% block content %}
    <div class="share">
        <div class="container-xl">
            {% if sent %}
            <h1>邮件发送</h1>
            <p>"{{ post.title  }}" 已成功发送到 {{ form.cleaned_data.to }}</p>
            {% else %}
            <h1>将 "{{ post.title }} 分享至朋友email</h1>
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="发送" >
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}